### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by lblaabjerg** [Acellera/moleculekit#118]
Hi, 

When I try to run `from moleculekit.occupancy_utils import calculate_occupancy` I get an import error:
> ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/lasbla/miniconda3/envs/thermonet/lib/python3.7/site-packages/moleculekit/occupancy_utils.cpython-37m-x86_64-linux-gnu.so)

My glibc version is 2.17, HTMD version is 2.0.6 with Python 3.7 installed in a fresh Miniconda environment. This is a follow-up question to: https://github.com/Acellera/htmd/issues/1043. 

Thank you in advance.

**Comment by stefdoerr** [comment]
Your operating system is too old. Older moleculekit versions were compiled unfortunately under a recent Ubuntu version and thus are not backwards compatible. In new moleculekit versions I compile them under a very old OS so that they are backwards compatible.
This practically leaves us only with the option of you compiling moleculekit manually. It's not too tricky though.
Do the following while having the HTMD conda environment active
```sh
conda list moleculekit # get the version from here
git clone https://github.com/Acellera/moleculekit
cd moleculekit
git checkout VERSION_FROM_ABOVE_COMMAND
pip install .
```
This should re-compile all the cython modules with your system's glibc version.

**Comment by lblaabjerg** [comment]
Thanks Stefan. I tried following your instructions and now get this error:

**Comment by stefdoerr** [comment]
That is fixed on master https://github.com/Acellera/moleculekit/blob/main/moleculekit/tmalign/src/TMAlign.cpp#L450
Overwrite your TMAlign.cpp file with the one linked here and try again.
