### ISSUE TITLE
error with hold_nonpeptidic_bonds=False

### ISSUE THREAD

**Issue by dargen3** [Acellera/moleculekit#137]
Hello,

I'd like to report a probable bug. The structure used is [9BFL](https://www.rcsb.org/structure/9BFL). If I run the systemPrepare function on this structure with hold_nonpeptidic_bonds=False, I get an error:

```
Traceback (most recent call last):
  File "/home/dargen3/Downloads/script.py", line 5, in <module>
    prepared_molecule = systemPrepare(molecule, pH=7, hold_nonpeptidic_bonds=False)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dargen3/miniconda3/lib/python3.11/site-packages/moleculekit/tools/preparation.py", line 756, in systemPrepare
    _no_opt, _no_prot, _no_titr = _get_hold_residues(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/home/dargen3/miniconda3/lib/python3.11/site-packages/moleculekit/tools/preparation.py", line 412, in _get_hold_residues
    if len(nonpeptidic_bonds) != 0:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
```

Script to reproduce the error:

```python
from moleculekit import molecule as molit
from moleculekit.tools.preparation import systemPrepare
molecule = molit.Molecule(f"9bfl.cif")
prepared_molecule = systemPrepare(molecule, pH=7, hold_nonpeptidic_bonds=False)
prepared_molecule.write(f"protonated_protein.cif")
```

I'd like to ask one more question. If the heteroresidue is bound to a protein (as in the 9BFL structure) and I use systemPrepare with hold_nonpeptidic_bonds=True, the residue to which the heteroresidue is bound is ignored and not protonated. If I use systemPrepare with hold_nonpeptidic_bonds=False, the residue to which the heteroresidue is bound is protonated but the ligand is ignored. Is there any way to use moleculekit to protonate the residue bound to the heteroresidue without ignoring the heteroresidue, please? Or does moleculekit not know how to handle this case?

**Comment by stefdoerr** [comment]
Thanks for the bug report! I fixed the issue now on the master branch. A new release will follow shortly

As to the second question, it's correct that it doesn't protonate the second residue. We don't provide the automatic functionality in moleculekit but the essence of it is that you need to protonate and reparameterize the whole heteroresidue with the bound ligand. This requires renaming the whole thing (residue+ligand), protonating them with a tool like AcePrep, parameterizing it with two caps at the end with a tool like Parameterize and converting those parameters to something which AMBER can use for building with teLeap.
We do provide functionality for this for more commercial applications, otherwise it's left to you to do it a bit manually. If you want to go that way take a look at 

https://open.playmolecule.org/tools/aceprep
https://open.playmolecule.org/tools/parameterize
https://github.com/Acellera/htmd/blob/master/htmd/builder/noncanonical.py

**Comment by stefdoerr** [comment]
RDKit broke everything again https://github.com/Acellera/moleculekit/actions/runs/10768214246/job/29856932103
so it will take some time for a new release. Sorry for that

**Comment by stefdoerr** [comment]
version 1.9.9 is out now
