### ISSUE TITLE
SmallMol object missing getCoords() function

### ISSUE THREAD

**Issue by albertma-evotec** [Acellera/moleculekit#26]
Was there ever a getCoords() function in the SmallMol object? 

A module released in this literature (https://github.com/compsciencelab/ligdream) (7 months old) try to call this function and I get an error.

Thanks

**Comment by stefdoerr** [comment]
You are going to have a bad time if you are trying to use LigDream with the new HTMD. In the docs of ligdream it says:
> Model training is written in pytorch==0.3.1 and uses keras==2.2.2 for data loaders. RDKit==2017.09.2.0 and HTMD==1.13.9 are needed for molecule manipulation.

So try to install HTMD 1.13.9. Otherwise feel free to use the new version but stuff has changed as you can see so you will have to go into the source code to find the changes. For this case you can replace `sm.getCoords()` with `sm.get('coords')` but I'm sure you will hit a good amount more issues like that.
